version: "3.9"

services:
  mysql-backup:
    build: .
    container_name: mysql-backup
    volumes:
      - ./backups:/backups
    extra_hosts:
      - "host.docker.internal:host-gateway"
    restart: unless-stopped
